name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.101
    - name: Build with dotnet
      run: dotnet build "./BSGO Server" --configuration Release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - This is a test
        files: |
          ./BSGO Server/BSGO Server/bin/Release/netcoreapp3.0/BSGO Server.deps.json
          ./BSGO Server/BSGO Server/bin/Release/netcoreapp3.0/BSGO Server.dll
          ./BSGO Server/BSGO Server/bin/Release/netcoreapp3.0/BSGO Server.exe
          ./BSGO Server/BSGO Server/bin/Release/netcoreapp3.0/BSGO Server.pdb
          ./BSGO Server/BSGO Server/bin/Release/netcoreapp3.0/BSGO Server.runtimeconfig.dev.json
          ./BSGO Server/BSGO Server/bin/Release/netcoreapp3.0/BSGO Server.runtimeconfig.json
          ./BSGO Server/BSGO Server/bin/Release/netcoreapp3.0/DnsClient.dll
          ./BSGO Server/BSGO Server/bin/Release/netcoreapp3.0/MongoDB.Bson.dll
          ./BSGO Server/BSGO Server/bin/Release/netcoreapp3.0/MongoDB.Driver.Core.dll
          ./BSGO Server/BSGO Server/bin/Release/netcoreapp3.0/MongoDB.Driver.dll
          ./BSGO Server/BSGO Server/bin/Release/netcoreapp3.0/SharpCompress.dll
